### ISSUE TITLE
API versioning support

### ISSUE THREAD

**Issue by Mohsen-Bazmi** [ScenarioHunting/ScenarioHunting#8]
It would be better to [semantic version](https://semver.org/) the API.

Current API looks like this:
````yaml
scenario: ...
given: ...
when: ...
then: ...
subject: ...
context: ...
````

With semantic versioning, it should look like this:
````yaml
version: 1.0.0
scenario: ...
given: ...
when: ...
then: ...
subject: ...
context: ...
````
### Steps
- [ ] Open the api.ts file
- [ ] Add version: 1.0.0
- [ ] Let the compiler lead you to fix the errors
